"""create zones and trips

Revision ID: 186e73c3687b
Revises: a434bc9598b9
Create Date: 2026-07-31 00:00:13.500690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186e73c3687b'
down_revision: Union[str, None] = 'a434bc9598b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('truck_id', sa.UUID(), nullable=False),
    sa.Column('origin_zone_id', sa.UUID(), nullable=False),
    sa.Column('destination_zone_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='in_progress', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name='ck_trips_status'),
    sa.ForeignKeyConstraint(['destination_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['origin_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_truck_id'), 'trips', ['truck_id'], unique=False)
    # ### end Alembic commands ###

    # Deny all access via PostgREST (anon/authenticated) by default until
    # explicit policies are defined. The backend connects with the pooler
    # user, which bypasses RLS.
    op.execute("ALTER TABLE zones ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE trips ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_truck_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('zones')
    # ### end Alembic commands ###
