"""add amount to trips, create trip_cars

Revision ID: a1b05037e3ac
Revises: a542b6bc2240
Create Date: 2026-07-31 00:48:07.702907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b05037e3ac'
down_revision: Union[str, None] = 'a542b6bc2240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_cars',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('vin_photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_cars_trip_id'), 'trip_cars', ['trip_id'], unique=False)
    op.add_column('trips', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###

    op.execute("ALTER TABLE trip_cars ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'amount')
    op.drop_index(op.f('ix_trip_cars_trip_id'), table_name='trip_cars')
    op.drop_table('trip_cars')
    # ### end Alembic commands ###
