"""add email full_name cedula to profiles

Revision ID: a542b6bc2240
Revises: 186e73c3687b
Create Date: 2026-07-31 00:24:18.973513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a542b6bc2240'
down_revision: Union[str, None] = '186e73c3687b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('cedula', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['cedula'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'cedula')
    op.drop_column('profiles', 'full_name')
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###
